[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  name = "github.com/fatih/structs"
  version = "1.0.0"

[[constraint]]
  name = "github.com/ghetzel/cli"
  branch = "master"

[[constraint]]
  name = "github.com/ghetzel/go-stockutil"
  version = ">=1.2.5"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jbenet/go-base58"
  version = "1.0.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[constraint]]
  name = "github.com/montanaflynn/stats"
  version = "0.2.0"

[[constraint]]
  name = "github.com/op/go-logging"
  branch = "master"

[[constraint]]
  name = "github.com/russross/blackfriday"
  version = "<2.0.0"

[[constraint]]
  name = "github.com/spaolacci/murmur3"
  version = "1.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"
