---
apiVersion: v1
kind: Pod
metadata:
  name: "build-${BUILDKITE_PIPELINE_NAME}-${BUILDKITE_PIPELINE_DEFAULT_BRANCH}"
spec:
  initContainers:
    - name: git-clone
      image: ghetzel/makebox:go1.13.7
      command: ["git", "clone", "--verbose", "--branch", "${BUILDKITE_BRANCH}", "${BUILDKITE_REPO}", "/projects"]
  containers:
    - name: build
      image: ghetzel/makebox:go1.13.7
      command: ["make"]
