---
steps:
  # - label: "Build via K8S"
  #   command: "bash -x .buildkite/deploy"
  #   concurrency: 1
  #   concurrency_group: builds
  - plugins:
      - EmbarkStudios/k8s:
          image: "ghetzel/makebox:1.13.7"
          always-pull: true
          command: ["env"]
