---
on: push
name: Test
jobs:
  run:
    container:
      image: ghetzel/makebox:go1.13.7

    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Test
        run: make test
