---
name: build
on:
  push:
    branches:
      - master
    paths:
      - "/Dockerfile"
      - "/Makefile"
      - "/version.go"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push Docker images
    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: make test

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Dockerfiles
        run: make docker
